package appcostal.model;
// Generated 27-may-2014 9:14:37 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Hermano generated by hbm2java
 */
public class Hermano  implements java.io.Serializable {


     private String dni;
     private String nombre;
     private String apellido1;
     private String apellido2;
     private String direccion;
     private String localidad;
     private String provincia;
     private String telefonofijo;
     private String telefonomovil;
     private Date fechanacimiento;
     private String clave;
     private String tipo;
     private String email;

    public Hermano() {
    }

    public Hermano(String dni, String nombre, String apellido1, String apellido2, String direccion, String localidad, String provincia, String telefonofijo, String telefonomovil, Date fechanacimiento, String clave, String tipo, String email) {
       this.dni = dni;
       this.nombre = nombre;
       this.apellido1 = apellido1;
       this.apellido2 = apellido2;
       this.direccion = direccion;
       this.localidad = localidad;
       this.provincia = provincia;
       this.telefonofijo = telefonofijo;
       this.telefonomovil = telefonomovil;
       this.fechanacimiento = fechanacimiento;
       this.clave = clave;
       this.tipo = tipo;
       this.email = email;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido1() {
        return this.apellido1;
    }
    
    public void setApellido1(String apellido1) {
        this.apellido1 = apellido1;
    }
    public String getApellido2() {
        return this.apellido2;
    }
    
    public void setApellido2(String apellido2) {
        this.apellido2 = apellido2;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getTelefonofijo() {
        return this.telefonofijo;
    }
    
    public void setTelefonofijo(String telefonofijo) {
        this.telefonofijo = telefonofijo;
    }
    public String getTelefonomovil() {
        return this.telefonomovil;
    }
    
    public void setTelefonomovil(String telefonomovil) {
        this.telefonomovil = telefonomovil;
    }
    public Date getFechanacimiento() {
        return this.fechanacimiento;
    }
    
    public void setFechanacimiento(Date fechanacimiento) {
        this.fechanacimiento = fechanacimiento;
    }
    public String getClave() {
        return this.clave;
    }
    
    public void setClave(String clave) {
        this.clave = clave;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


