package appcostal.model;
// Generated 27-may-2014 9:14:37 by Hibernate Tools 3.6.0



/**
 * Marcha generated by hbm2java
 */
public class Marcha  implements java.io.Serializable {


     private Integer idmarcha;
     private String nombre;
     private int duracion;

    public Marcha() {
    }

    public Marcha(String nombre, int duracion) {
       this.nombre = nombre;
       this.duracion = duracion;
    }
   
    public Integer getIdmarcha() {
        return this.idmarcha;
    }
    
    public void setIdmarcha(Integer idmarcha) {
        this.idmarcha = idmarcha;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public int getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(int duracion) {
        this.duracion = duracion;
    }




}


