package appcostal.model;
// Generated 27-may-2014 9:14:37 by Hibernate Tools 3.6.0



/**
 * RelEventoHermano generated by hbm2java
 */
public class RelEventoHermano  implements java.io.Serializable {


     private RelEventoHermanoId id;
     private boolean asiste;

    public RelEventoHermano() {
    }

    public RelEventoHermano(RelEventoHermanoId id, boolean asiste) {
       this.id = id;
       this.asiste = asiste;
    }
   
    public RelEventoHermanoId getId() {
        return this.id;
    }
    
    public void setId(RelEventoHermanoId id) {
        this.id = id;
    }
    public boolean isAsiste() {
        return this.asiste;
    }
    
    public void setAsiste(boolean asiste) {
        this.asiste = asiste;
    }




}


