package appcostal.model;
// Generated 27-may-2014 9:14:37 by Hibernate Tools 3.6.0



/**
 * RelHermanoPaso generated by hbm2java
 */
public class RelHermanoPaso  implements java.io.Serializable {


     private RelHermanoPasoId id;
     private boolean escapataz;
     private boolean escostalero;

    public RelHermanoPaso() {
    }

    public RelHermanoPaso(RelHermanoPasoId id, boolean escapataz, boolean escostalero) {
       this.id = id;
       this.escapataz = escapataz;
       this.escostalero = escostalero;
    }
   
    public RelHermanoPasoId getId() {
        return this.id;
    }
    
    public void setId(RelHermanoPasoId id) {
        this.id = id;
    }
    public boolean isEscapataz() {
        return this.escapataz;
    }
    
    public void setEscapataz(boolean escapataz) {
        this.escapataz = escapataz;
    }
    public boolean isEscostalero() {
        return this.escostalero;
    }
    
    public void setEscostalero(boolean escostalero) {
        this.escostalero = escostalero;
    }




}


