package appcostal.model;
// Generated 27-may-2014 9:14:37 by Hibernate Tools 3.6.0



/**
 * RelIgualaHermano generated by hbm2java
 */
public class RelIgualaHermano  implements java.io.Serializable {


     private RelIgualaHermanoId id;
     private float altura;

    public RelIgualaHermano() {
    }

    public RelIgualaHermano(RelIgualaHermanoId id, float altura) {
       this.id = id;
       this.altura = altura;
    }
   
    public RelIgualaHermanoId getId() {
        return this.id;
    }
    
    public void setId(RelIgualaHermanoId id) {
        this.id = id;
    }
    public float getAltura() {
        return this.altura;
    }
    
    public void setAltura(float altura) {
        this.altura = altura;
    }




}


