package appcostal.model;
// Generated 27-may-2014 9:14:37 by Hibernate Tools 3.6.0



/**
 * RelRelevoTrabajaderaHermano generated by hbm2java
 */
public class RelRelevoTrabajaderaHermano  implements java.io.Serializable {


     private RelRelevoTrabajaderaHermanoId id;

    public RelRelevoTrabajaderaHermano() {
    }

    public RelRelevoTrabajaderaHermano(RelRelevoTrabajaderaHermanoId id) {
       this.id = id;
    }
   
    public RelRelevoTrabajaderaHermanoId getId() {
        return this.id;
    }
    
    public void setId(RelRelevoTrabajaderaHermanoId id) {
        this.id = id;
    }




}


