package appcostal.model;
// Generated 14-may-2014 3:10:36 by Hibernate Tools 3.6.0



/**
 * Trabajadera generated by hbm2java
 */
public class Trabajadera  implements java.io.Serializable {


     private TrabajaderaId id;
     private int ncostaleros;

    public Trabajadera() {
    }

    public Trabajadera(TrabajaderaId id, int ncostaleros) {
       this.id = id;
       this.ncostaleros = ncostaleros;
    }
   
    public TrabajaderaId getId() {
        return this.id;
    }
    
    public void setId(TrabajaderaId id) {
        this.id = id;
    }
    public int getNcostaleros() {
        return this.ncostaleros;
    }
    
    public void setNcostaleros(int ncostaleros) {
        this.ncostaleros = ncostaleros;
    }




}


