package appcostal.model;
// Generated 14-may-2014 3:10:36 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Hermandad generated by hbm2java
 */
public class Hermandad  implements java.io.Serializable {


     private Integer idhermandad;
     private String nombre;
     private String sede;
     private Set pasos = new HashSet(0);

    public Hermandad() {
    }

	
    public Hermandad(String nombre, String sede) {
        this.nombre = nombre;
        this.sede = sede;
    }
    public Hermandad(String nombre, String sede, Set pasos) {
       this.nombre = nombre;
       this.sede = sede;
       this.pasos = pasos;
    }
   
    public Integer getIdhermandad() {
        return this.idhermandad;
    }
    
    public void setIdhermandad(Integer idhermandad) {
        this.idhermandad = idhermandad;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getSede() {
        return this.sede;
    }
    
    public void setSede(String sede) {
        this.sede = sede;
    }
    public Set getPasos() {
        return this.pasos;
    }
    
    public void setPasos(Set pasos) {
        this.pasos = pasos;
    }




}


