package appcostal.model;
// Generated 14-may-2014 3:10:36 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Iguala generated by hbm2java
 */
public class Iguala  implements java.io.Serializable {


     private Integer idiguala;
     private Paso paso;
     private String descripcion;
     private Date fecha;

    public Iguala() {
    }

	
    public Iguala(Paso paso) {
        this.paso = paso;
    }
    public Iguala(Paso paso, String descripcion, Date fecha) {
       this.paso = paso;
       this.descripcion = descripcion;
       this.fecha = fecha;
    }
   
    public Integer getIdiguala() {
        return this.idiguala;
    }
    
    public void setIdiguala(Integer idiguala) {
        this.idiguala = idiguala;
    }
    public Paso getPaso() {
        return this.paso;
    }
    
    public void setPaso(Paso paso) {
        this.paso = paso;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }




}


