package appcostal.model;
// Generated 14-may-2014 3:10:36 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Recorrido generated by hbm2java
 */
public class Recorrido  implements java.io.Serializable {


     private Integer idrecorrido;
     private String descripcion;
     private Set procesions = new HashSet(0);

    public Recorrido() {
    }

	
    public Recorrido(String descripcion) {
        this.descripcion = descripcion;
    }
    public Recorrido(String descripcion, Set procesions) {
       this.descripcion = descripcion;
       this.procesions = procesions;
    }
   
    public Integer getIdrecorrido() {
        return this.idrecorrido;
    }
    
    public void setIdrecorrido(Integer idrecorrido) {
        this.idrecorrido = idrecorrido;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getProcesions() {
        return this.procesions;
    }
    
    public void setProcesions(Set procesions) {
        this.procesions = procesions;
    }




}


