package appcostal.model;
// Generated 14-may-2014 3:10:36 by Hibernate Tools 3.6.0



/**
 * TrabajaderaId generated by hbm2java
 */
public class TrabajaderaId  implements java.io.Serializable {


     private int idtrabajadera;
     private int idpaso;

    public TrabajaderaId() {
    }

    public TrabajaderaId(int idtrabajadera, int idpaso) {
       this.idtrabajadera = idtrabajadera;
       this.idpaso = idpaso;
    }
   
    public int getIdtrabajadera() {
        return this.idtrabajadera;
    }
    
    public void setIdtrabajadera(int idtrabajadera) {
        this.idtrabajadera = idtrabajadera;
    }
    public int getIdpaso() {
        return this.idpaso;
    }
    
    public void setIdpaso(int idpaso) {
        this.idpaso = idpaso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TrabajaderaId) ) return false;
		 TrabajaderaId castOther = ( TrabajaderaId ) other; 
         
		 return (this.getIdtrabajadera()==castOther.getIdtrabajadera())
 && (this.getIdpaso()==castOther.getIdpaso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdtrabajadera();
         result = 37 * result + this.getIdpaso();
         return result;
   }   


}


