package appcostal.model;
// Generated 27-may-2014 23:53:05 by Hibernate Tools 3.6.0


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Evento generated by hbm2java
 */
public class Evento  implements java.io.Serializable {


     private Integer idevento;
     private Paso paso;
     private Date fecha;
     private String descripcion;
     private Set relEventoHermanos = new HashSet(0);

    public Evento() {
    }

	
    public Evento(Paso paso, Date fecha, String descripcion) {
        this.paso = paso;
        this.fecha = fecha;
        this.descripcion = descripcion;
    }
    public Evento(Paso paso, Date fecha, String descripcion, Set relEventoHermanos) {
       this.paso = paso;
       this.fecha = fecha;
       this.descripcion = descripcion;
       this.relEventoHermanos = relEventoHermanos;
    }
   
    public Integer getIdevento() {
        return this.idevento;
    }
    
    public void setIdevento(Integer idevento) {
        this.idevento = idevento;
    }
    public Paso getPaso() {
        return this.paso;
    }
    
    public void setPaso(Paso paso) {
        this.paso = paso;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Set getRelEventoHermanos() {
        return this.relEventoHermanos;
    }
    
    public void setRelEventoHermanos(Set relEventoHermanos) {
        this.relEventoHermanos = relEventoHermanos;
    }




}


