package appcostal.model;
// Generated 27-may-2014 23:28:15 by Hibernate Tools 3.6.0



/**
 * Posicion generated by hbm2java
 */
public class Posicion  implements java.io.Serializable {


     private Integer idposicion;
     private String descripcion;

    public Posicion() {
    }

    public Posicion(String descripcion) {
       this.descripcion = descripcion;
    }
   
    public Integer getIdposicion() {
        return this.idposicion;
    }
    
    public void setIdposicion(Integer idposicion) {
        this.idposicion = idposicion;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }




}


