package appcostal.model;
// Generated 27-may-2014 13:22:48 by Hibernate Tools 3.6.0



/**
 * RelEventoHermanoId generated by hbm2java
 */
public class RelEventoHermanoId  implements java.io.Serializable {


     private int idevento;
     private String dni;

    public RelEventoHermanoId() {
    }

    public RelEventoHermanoId(int idevento, String dni) {
       this.idevento = idevento;
       this.dni = dni;
    }
   
    public int getIdevento() {
        return this.idevento;
    }
    
    public void setIdevento(int idevento) {
        this.idevento = idevento;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelEventoHermanoId) ) return false;
		 RelEventoHermanoId castOther = ( RelEventoHermanoId ) other; 
         
		 return (this.getIdevento()==castOther.getIdevento())
 && ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdevento();
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         return result;
   }   


}


