package appcostal.model;
// Generated 27-may-2014 13:22:48 by Hibernate Tools 3.6.0



/**
 * RelHermanoPasoId generated by hbm2java
 */
public class RelHermanoPasoId  implements java.io.Serializable {


     private String dni;
     private int idpaso;

    public RelHermanoPasoId() {
    }

    public RelHermanoPasoId(String dni, int idpaso) {
       this.dni = dni;
       this.idpaso = idpaso;
    }
   
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getIdpaso() {
        return this.idpaso;
    }
    
    public void setIdpaso(int idpaso) {
        this.idpaso = idpaso;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelHermanoPasoId) ) return false;
		 RelHermanoPasoId castOther = ( RelHermanoPasoId ) other; 
         
		 return ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) )
 && (this.getIdpaso()==castOther.getIdpaso());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         result = 37 * result + this.getIdpaso();
         return result;
   }   


}


