package appcostal.model;
// Generated 27-may-2014 23:53:05 by Hibernate Tools 3.6.0



/**
 * RelHermanoPaso generated by hbm2java
 */
public class RelHermanoPaso  implements java.io.Serializable {


     private RelHermanoPasoId id;
     private Paso paso;
     private Hermano hermano;
     private boolean escapataz;
     private boolean escostalero;

    public RelHermanoPaso() {
    }

    public RelHermanoPaso(RelHermanoPasoId id, Paso paso, Hermano hermano, boolean escapataz, boolean escostalero) {
       this.id = id;
       this.paso = paso;
       this.hermano = hermano;
       this.escapataz = escapataz;
       this.escostalero = escostalero;
    }
   
    public RelHermanoPasoId getId() {
        return this.id;
    }
    
    public void setId(RelHermanoPasoId id) {
        this.id = id;
    }
    public Paso getPaso() {
        return this.paso;
    }
    
    public void setPaso(Paso paso) {
        this.paso = paso;
    }
    public Hermano getHermano() {
        return this.hermano;
    }
    
    public void setHermano(Hermano hermano) {
        this.hermano = hermano;
    }
    public boolean isEscapataz() {
        return this.escapataz;
    }
    
    public void setEscapataz(boolean escapataz) {
        this.escapataz = escapataz;
    }
    public boolean isEscostalero() {
        return this.escostalero;
    }
    
    public void setEscostalero(boolean escostalero) {
        this.escostalero = escostalero;
    }




}


