package appcostal.model;
// Generated 27-may-2014 23:53:05 by Hibernate Tools 3.6.0



/**
 * RelIgualaHermano generated by hbm2java
 */
public class RelIgualaHermano  implements java.io.Serializable {


     private RelIgualaHermanoId id;
     private Iguala iguala;
     private Hermano hermano;
     private float altura;

    public RelIgualaHermano() {
    }

    public RelIgualaHermano(RelIgualaHermanoId id, Iguala iguala, Hermano hermano, float altura) {
       this.id = id;
       this.iguala = iguala;
       this.hermano = hermano;
       this.altura = altura;
    }
   
    public RelIgualaHermanoId getId() {
        return this.id;
    }
    
    public void setId(RelIgualaHermanoId id) {
        this.id = id;
    }
    public Iguala getIguala() {
        return this.iguala;
    }
    
    public void setIguala(Iguala iguala) {
        this.iguala = iguala;
    }
    public Hermano getHermano() {
        return this.hermano;
    }
    
    public void setHermano(Hermano hermano) {
        this.hermano = hermano;
    }
    public float getAltura() {
        return this.altura;
    }
    
    public void setAltura(float altura) {
        this.altura = altura;
    }




}


