package appcostal.model;
// Generated 27-may-2014 13:22:48 by Hibernate Tools 3.6.0



/**
 * RelMarchaProcesion generated by hbm2java
 */
public class RelMarchaProcesion  implements java.io.Serializable {


     private RelMarchaProcesionId id;
     private String lugar;

    public RelMarchaProcesion() {
    }

    public RelMarchaProcesion(RelMarchaProcesionId id, String lugar) {
       this.id = id;
       this.lugar = lugar;
    }
   
    public RelMarchaProcesionId getId() {
        return this.id;
    }
    
    public void setId(RelMarchaProcesionId id) {
        this.id = id;
    }
    public String getLugar() {
        return this.lugar;
    }
    
    public void setLugar(String lugar) {
        this.lugar = lugar;
    }




}


