package appcostal.model;
// Generated 27-may-2014 13:22:48 by Hibernate Tools 3.6.0



/**
 * RelRelevoTrabajaderaHermanoId generated by hbm2java
 */
public class RelRelevoTrabajaderaHermanoId  implements java.io.Serializable {


     private int idrelevo;
     private int idtrabajadera;
     private String dni;
     private int idposicion;

    public RelRelevoTrabajaderaHermanoId() {
    }

    public RelRelevoTrabajaderaHermanoId(int idrelevo, int idtrabajadera, String dni, int idposicion) {
       this.idrelevo = idrelevo;
       this.idtrabajadera = idtrabajadera;
       this.dni = dni;
       this.idposicion = idposicion;
    }
   
    public int getIdrelevo() {
        return this.idrelevo;
    }
    
    public void setIdrelevo(int idrelevo) {
        this.idrelevo = idrelevo;
    }
    public int getIdtrabajadera() {
        return this.idtrabajadera;
    }
    
    public void setIdtrabajadera(int idtrabajadera) {
        this.idtrabajadera = idtrabajadera;
    }
    public String getDni() {
        return this.dni;
    }
    
    public void setDni(String dni) {
        this.dni = dni;
    }
    public int getIdposicion() {
        return this.idposicion;
    }
    
    public void setIdposicion(int idposicion) {
        this.idposicion = idposicion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RelRelevoTrabajaderaHermanoId) ) return false;
		 RelRelevoTrabajaderaHermanoId castOther = ( RelRelevoTrabajaderaHermanoId ) other; 
         
		 return (this.getIdrelevo()==castOther.getIdrelevo())
 && (this.getIdtrabajadera()==castOther.getIdtrabajadera())
 && ( (this.getDni()==castOther.getDni()) || ( this.getDni()!=null && castOther.getDni()!=null && this.getDni().equals(castOther.getDni()) ) )
 && (this.getIdposicion()==castOther.getIdposicion());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdrelevo();
         result = 37 * result + this.getIdtrabajadera();
         result = 37 * result + ( getDni() == null ? 0 : this.getDni().hashCode() );
         result = 37 * result + this.getIdposicion();
         return result;
   }   


}


